name: Tests on scrappy_python

on:
  pull_request:
    branches:
      - main
      - develop
      - '**'
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run:  |
          # Clone et installe pyro-engine dans /tmp
          git clone https://github.com/pyronear/pyro-engine.git /tmp/pyro-engine
          pip install -r /tmp/pyro-engine/requirements.txt
          pip install -e /tmp/pyro-engine
          
          # Installe les dépendances du projet actuel
          pip install -r ./scrapy_pyronear/requirements.txt

      - name: Run tests
        run: pytest ./scrapy_pyronear/tests
