name: Tests on scrappy_python

on:
  pull_request:
    branches:
      - main
      - develop
      - '**'
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run:  |
          # Clone and install pyro-engine in /tmp
          git clone https://github.com/pyronear/pyro-engine.git /tmp/pyro-engine
          pip install -r /tmp/pyro-engine/requirements.txt
          pip install -e /tmp/pyro-engine

          # Clone and install pyro-annotator annotation_api in /tmp
          git clone https://github.com/pyronear/pyro-annotator.git /tmp/pyro-annotator
          pip install -e /tmp/pyro-annotator/annotation_api
          
          # Install current project dependencies
          pip install -r ./alertwest_scraping/requirements.txt
          
          # Install the package in editable mode
          pip install -e .

      - name: Run tests
        run: pytest ./alertwest_scraping/tests
