name: Tests on scrappy_python

on:
  pull_request:
    branches:
      - main
      - develop
      - '**'
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run:  |
          # Clone et installe pyro-engine
          git clone https://github.com/pyronear/pyro-engine.git
          cd pyro-engine
          pip install -r requirements.txt
          pip install -e .
          cd ..
          
          # Installe les dépendances du projet actuel
          pip install -r ./scrapy_pyronear/requirements.txt

          # Install the scrapy_pyronear package
          pip install -e ./scrapy_pyronear

      - name: Run tests
        run: pytest ./scrapy_pyronear/tests
